### ISSUE TITLE
Gutenberg: Fatal error on "null" when no download is selected

### ISSUE THREAD

**Issue by jmslbam** [download-monitor/download-monitor#652]
## How to duplicatie

- Insert DLM block, but don't select a download.
- Save page.
- Voila, fatal error on frontpage. (but GB editor also crashes)

## Fix
Check in templates if `$dlm_download` is not `null`.

In my case: `templates/content-download-title.php`

```
<?php
/**
 * Shows title only.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

/** @var DLM_Download $dlm_download */
?>

<?php if( ! $dlm_download ) {
	return _e('No download found', 'download-monitor');
} ?>
<a class="download-link" title="<?php if ( ! is_null( $dlm_download ) && $dlm_download->get_version()->has_version_number() ) {
	printf( __( 'Version %s', 'download-monitor' ), $dlm_download->get_version()->get_version_number() );
} ?>" href="<?php $dlm_download->the_download_link(); ?>" rel="nofollow">
	<?php $dlm_download->the_title(); ?>
</a>
```

## The error
```
Fatal error: Uncaught Error: Call to a member function get_version() on null in /nas/content/xxx/xxx/wp-content/plugins/download-monitor/templates/content-download-title.php:12\nStack trace:\n#0 /nas/content/xxx/xxx/wp-content/plugins/download-monitor/src/TemplateHandler.php(90): include()\n#1 /nas/content/xxx/xxx/wp-content/plugins/download-monitor/src/Gutenberg.php(111): DLM_Template_Handler->get_template_part('content-downloa...', 'title', '', Array)\n#2 /nas/content/xxx/xxx/wp-includes/class-wp-block.php(217): DLM_Gutenberg->render_download_button(Array, '', Object(WP_Block))\n#3 /nas/content/xxx/xxx/wp-includes/blocks.php(720): WP_Block->render()\n#4 /nas/content/xxx/xxx/wp-includes/blocks.php(758): render_block(Array)\n#5 /nas/content/xxx/xxx/wp-includes/class-wp-hook.php(287): do_blocks('<!-- wp:downloa...')\n#6 /nas/content/xxx/xxx/wp-includes/plugin.php(206): WP_Hook->apply_filters('<!-- wp:downloa...', Array)\n#7 /nas/content/xxx/xxx/wp-includes/post-template.php(253): apply_filters('t in /nas/content/xxx/xxx/wp-content/plugins/download-monitor/templates/content-download-title.php on line 12, referer: https://members.iab-ingenieurs.nl/wp-admin/edit.php?post_type=sfwd-lessons
```

Doeg!

**Comment by jmslbam** [comment]
We have a feelings that this happend when WordPress "autosaved" the post.

**Comment by jmslbam** [comment]
Aha, there already was an issue in the DLM repo... found a duplicate here #601 

cc @boemedia, I don't think this will be fixed in the near future as the original issue is from june 2019, so I will fix this by adding a check in a copy of our templates in our own theme. 👍
